// <auto-generated />
using System;
using Basico.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Basico.Migrations
{
    [DbContext(typeof(ApiContext))]
    [Migration("20240302191039_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Basico.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DescricaoCategoria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("Basico.Models.Cor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoCor")
                        .HasColumnType("text");

                    b.Property<string>("CorReferencia")
                        .HasColumnType("text");

                    b.Property<string>("NomeCor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Cores");
                });

            modelBuilder.Entity("Basico.Models.Material", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<int>("CodigoMaterial")
                        .HasColumnType("integer");

                    b.Property<string>("Composicao")
                        .HasColumnType("text");

                    b.Property<string>("ConversaoMedida")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CoresId")
                        .HasColumnType("integer");

                    b.Property<string>("DescricaoMaterial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FotoMaterial")
                        .HasColumnType("text");

                    b.Property<string>("Gramatura")
                        .HasColumnType("text");

                    b.Property<string>("Largura")
                        .HasColumnType("text");

                    b.Property<double>("Preco")
                        .HasColumnType("double precision");

                    b.Property<double?>("PrecoMedida")
                        .HasColumnType("double precision");

                    b.Property<int>("UnidadeCompraId")
                        .HasColumnType("integer");

                    b.Property<int>("UnidadeMedidaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("CoresId");

                    b.HasIndex("UnidadeMedidaId");

                    b.ToTable("Materiais");
                });

            modelBuilder.Entity("Basico.Models.UnidadeMedida", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AbreviacaoMedida")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DescricaoMedida")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("UnidadesMedida");
                });

            modelBuilder.Entity("Basico.Models.Material", b =>
                {
                    b.HasOne("Basico.Models.Categoria", "Categorias")
                        .WithMany()
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Basico.Models.Cor", "Cores")
                        .WithMany()
                        .HasForeignKey("CoresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Basico.Models.UnidadeMedida", "UnidadesMedida")
                        .WithMany()
                        .HasForeignKey("UnidadeMedidaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categorias");

                    b.Navigation("Cores");

                    b.Navigation("UnidadesMedida");
                });
#pragma warning restore 612, 618
        }
    }
}
